"""Helper functions for SPORE Streamlit dashboard."""

import asyncio
import json
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).parent.parent
# Single source of truth for run state: the live progress file written by
# the pipeline's ProgressTracker. Legacy STATUS_FILE is no longer used.
PROGRESS_FILE = PROJECT_ROOT / ".spore_progress.json"


def run_async(coro):
    """Run an async coroutine in Streamlit."""
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    try:
        return loop.run_until_complete(coro)
    finally:
        loop.close()


def get_system_status() -> dict[str, Any]:
    """Get the current system status from .spore_progress.json.

    Returns the same shape the UI has always consumed
    ({"status", "run_id", "started_at", ...}) but reads from the live
    progress file written by the pipeline, so the status is always in
    sync with what the pipeline actually did (including 'failed' when
    the constitution guard kills a run).
    """
    if PROGRESS_FILE.exists():
        try:
            with open(PROGRESS_FILE) as f:
                data = json.load(f)
            return {
                "status": data.get("status", "idle"),
                "run_id": data.get("run_id"),
                "started_at": data.get("started_at"),
                "domain": data.get("domain"),
                "error": data.get("error_message"),
            }
        except (json.JSONDecodeError, IOError):
            pass
    return {"status": "idle", "run_id": None, "started_at": None}


def launch_run_background(
    n_collisions: int,
    domain: str,
    cross_ratio: float,
) -> str:
    """Launch a SPORE run in background subprocess.

    Returns the placeholder run_id used for UI feedback only — the real
    run_id is generated by run_pipeline and appears in .spore_progress.json
    within a second or two.
    """
    placeholder_run_id = f"run-{datetime.now().strftime('%Y%m%d-%H%M%S')}"

    cmd = [
        "python", "-m", "cli", "run",
        "--collisions", str(n_collisions),
        "--domain", domain,
    ]

    subprocess.Popen(
        cmd,
        cwd=PROJECT_ROOT,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        start_new_session=True,
    )

    return placeholder_run_id


def format_cost(cost: float) -> str:
    """Format cost in USD."""
    if cost < 0.01:
        return f"${cost:.4f}"
    elif cost < 1:
        return f"${cost:.3f}"
    else:
        return f"${cost:.2f}"


def format_rate(rate: float) -> str:
    """Format a rate as percentage."""
    return f"{rate * 100:.1f}%"


def get_status_emoji(status: str) -> str:
    """Get emoji for system status."""
    return {
        "idle": "🟢",
        "running": "🔄",
        "error": "🔴",
        "evolving": "🧬",
    }.get(status, "⚪")


def get_feedback_emoji(feedback: str | None) -> str:
    """Get emoji for human feedback."""
    if feedback is None:
        return "⏳"
    return {
        "trash": "🗑️",
        "interesting": "🤔",
        "want_to_test": "🔥",
    }.get(feedback, "❓")
