"""Helper functions for SPORE Streamlit dashboard."""

import asyncio
import json
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).parent.parent
# Single source of truth for run state: the live progress file written by
# the pipeline's ProgressTracker. Legacy STATUS_FILE is no longer used.
PROGRESS_FILE = PROJECT_ROOT / ".spore_progress.json"
RUN_LOGS_DIR = PROJECT_ROOT / "outputs" / "run_logs"


def _open_run_log(label: str) -> tuple[Path, Any]:
    """Create outputs/run_logs/<label>-<ts>.log and return (path, file-handle).

    The caller must hand the file handle to subprocess.Popen as stdout/stderr
    and is responsible for closing it. Prior to this, background subprocesses
    were launched with stdout/stderr=DEVNULL, which meant tracebacks from the
    pipeline (post-fire kills, LLM parse errors, etc.) were lost forever.
    """
    RUN_LOGS_DIR.mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d-%H%M%S")
    path = RUN_LOGS_DIR / f"{label}-{ts}.log"
    fh = open(path, "a", buffering=1, encoding="utf-8")  # line-buffered
    fh.write(f"# SPORE {label} launched at {datetime.now().isoformat()}\n")
    fh.flush()
    return path, fh


def run_async(coro):
    """Run an async coroutine in Streamlit."""
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    try:
        return loop.run_until_complete(coro)
    finally:
        loop.close()


def get_system_status() -> dict[str, Any]:
    """Get the current system status from .spore_progress.json.

    Returns the same shape the UI has always consumed
    ({"status", "run_id", "started_at", ...}) but reads from the live
    progress file written by the pipeline, so the status is always in
    sync with what the pipeline actually did (including 'failed' when
    the constitution guard kills a run).
    """
    if PROGRESS_FILE.exists():
        try:
            with open(PROGRESS_FILE) as f:
                data = json.load(f)
            return {
                "status": data.get("status", "idle"),
                "run_id": data.get("run_id"),
                "started_at": data.get("started_at"),
                "domain": data.get("domain"),
                "error": data.get("error_message"),
            }
        except (json.JSONDecodeError, IOError):
            pass
    return {"status": "idle", "run_id": None, "started_at": None}


def launch_run_background(
    n_collisions: int,
    domain: str,
    cross_ratio: float,
) -> tuple[str, Path]:
    """Launch a SPORE run in background subprocess.

    Returns ``(placeholder_run_id, log_path)``. ``placeholder_run_id`` is
    used for immediate UI feedback only — the real run_id is generated by
    run_pipeline and appears in .spore_progress.json within a second or two.
    ``log_path`` is a timestamped file under outputs/run_logs/ that captures
    stdout and stderr so the run is auditable after it finishes.
    """
    placeholder_run_id = f"run-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
    log_path, log_fh = _open_run_log(placeholder_run_id)

    cmd = [
        "python", "-m", "cli", "run",
        "--collisions", str(n_collisions),
        "--domain", domain,
    ]

    subprocess.Popen(
        cmd,
        cwd=PROJECT_ROOT,
        stdout=log_fh,
        stderr=subprocess.STDOUT,
        start_new_session=True,
    )
    # We intentionally do not close log_fh here — the child process inherits
    # the file descriptor via fork; the parent's handle is leaked but harmless
    # for a short-lived Streamlit request.

    return placeholder_run_id, log_path


def launch_post_fire_background(hypothesis_id: str) -> Path:
    """Launch a post-fire pipeline in a detached subprocess.

    Writes stdout + stderr to outputs/run_logs/post-fire-<hid>-<ts>.log.
    Returns the log path so the UI can surface it.
    """
    label = f"post-fire-{hypothesis_id[-12:]}"
    log_path, log_fh = _open_run_log(label)
    cmd = [
        str(PROJECT_ROOT / ".venv" / "bin" / "python"),
        "cli.py", "post-fire",
        "--hypothesis-id", hypothesis_id,
    ]
    subprocess.Popen(
        cmd,
        cwd=PROJECT_ROOT,
        stdout=log_fh,
        stderr=subprocess.STDOUT,
        start_new_session=True,
    )
    return log_path


def format_cost(cost: float) -> str:
    """Format cost in USD."""
    if cost < 0.01:
        return f"${cost:.4f}"
    elif cost < 1:
        return f"${cost:.3f}"
    else:
        return f"${cost:.2f}"


def format_rate(rate: float) -> str:
    """Format a rate as percentage."""
    return f"{rate * 100:.1f}%"


def get_status_emoji(status: str) -> str:
    """Get emoji for system status."""
    return {
        "idle": "🟢",
        "running": "🔄",
        "error": "🔴",
        "evolving": "🧬",
    }.get(status, "⚪")


def get_feedback_emoji(feedback: str | None) -> str:
    """Get emoji for human feedback."""
    if feedback is None:
        return "⏳"
    return {
        "trash": "🗑️",
        "interesting": "🤔",
        "want_to_test": "🔥",
    }.get(feedback, "❓")
