"""Mutation models for L1 genome evolution.

Based on Design Doc section 2.3 - Team L1 (Trainers).
"""

from datetime import datetime
from enum import Enum
from typing import Any, Optional
from uuid import uuid4

from pydantic import BaseModel, Field


class MutationType(str, Enum):
    """Types of mutations L1 can propose."""

    PROMPT_MODIFICATION = "prompt_modification"
    PARAMETER_CHANGE = "parameter_change"
    SOURCE_MODIFICATION = "source_modification"
    SCORE_WEIGHT_ADJUSTMENT = "score_weight_adjustment"
    DOMAIN_EXCLUSION = "domain_exclusion"
    STRATEGY_WEIGHT_CHANGE = "strategy_weight_change"


class MutationStatus(str, Enum):
    """Status of a mutation in its lifecycle."""

    PROPOSED = "proposed"
    VALIDATED = "validated"
    REJECTED = "rejected"
    APPLIED = "applied"
    ROLLED_BACK = "rolled_back"


class MutationRisk(str, Enum):
    """Risk level of a mutation."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class Mutation(BaseModel):
    """A proposed or applied mutation to the L0 genome."""

    id: str = Field(
        default_factory=lambda: f"MUT-{datetime.now().strftime('%Y%m%d')}-{uuid4().hex[:6]}",
        description="Unique mutation identifier"
    )
    created_at: datetime = Field(
        default_factory=datetime.now,
        description="When the mutation was proposed"
    )

    # What the mutation does
    type: MutationType = Field(..., description="Type of mutation")
    target_path: str = Field(
        ...,
        description="Path in genome YAML (e.g., 'agents.synthesis.parameters.max_tokens')"
    )
    old_value: Any = Field(..., description="Value before mutation")
    new_value: Any = Field(..., description="Value after mutation")

    # Justification
    description: str = Field(..., description="Human-readable description")
    justification: str = Field(
        ...,
        description="Data-driven justification for this mutation"
    )
    estimated_impact: str = Field(
        ...,
        description="Expected improvement from this mutation"
    )
    risk: MutationRisk = Field(
        default=MutationRisk.MEDIUM,
        description="Risk level"
    )

    # Source data
    based_on_run_id: Optional[str] = Field(
        None,
        description="Run ID that triggered this mutation"
    )
    observation_summary: Optional[str] = Field(
        None,
        description="Key observation that led to this mutation"
    )

    # Lifecycle
    status: MutationStatus = Field(
        default=MutationStatus.PROPOSED,
        description="Current status"
    )
    validated_at: Optional[datetime] = Field(None)
    applied_at: Optional[datetime] = Field(None)
    rolled_back_at: Optional[datetime] = Field(None)

    # Critic feedback
    critic_verdict: Optional[str] = Field(
        None,
        description="Verdict from L1 Critic"
    )
    critic_concerns: list[str] = Field(
        default_factory=list,
        description="Concerns raised by Critic"
    )

    # Results tracking
    metrics_before: Optional[dict[str, float]] = Field(
        None,
        description="Key metrics before applying mutation"
    )
    metrics_after: Optional[dict[str, float]] = Field(
        None,
        description="Key metrics after applying mutation"
    )
    rollback_reason: Optional[str] = Field(
        None,
        description="Reason for rollback if rolled back"
    )


class ObservationReport(BaseModel):
    """Report generated by L1 Observer from L0 metrics."""

    generated_at: datetime = Field(default_factory=datetime.now)
    analyzed_run_ids: list[str] = Field(
        default_factory=list,
        description="Run IDs included in this analysis"
    )

    # Run metrics
    total_collisions: int = Field(0)
    total_hypotheses: int = Field(0)
    total_curated: int = Field(0)
    bridge_rate: float = Field(0.0, description="Hypotheses / Collisions")
    curation_rate: float = Field(0.0, description="Curated / Hypotheses")

    # Score distributions
    avg_composite_score: float = Field(0.0)
    score_distribution: dict[str, float] = Field(
        default_factory=dict,
        description="Distribution of scores by bucket"
    )

    # Human feedback analysis
    feedback_distribution: dict[str, int] = Field(
        default_factory=dict,
        description="Count by feedback type (trash, interesting, want_to_test)"
    )
    score_feedback_correlation: Optional[float] = Field(
        None,
        description="Correlation between composite score and positive feedback"
    )

    # Gap analysis
    top_data_gaps: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Most recurring data gaps"
    )
    top_competence_gaps: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Most recurring competence gaps"
    )
    top_epistemic_gaps: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Most recurring epistemic gaps"
    )

    # Domain analysis
    domain_fertility: dict[str, dict[str, float]] = Field(
        default_factory=dict,
        description="Per-domain metrics (bridge_rate, avg_score, feedback_ratio)"
    )
    overexploited_domains: list[str] = Field(
        default_factory=list,
        description="Domains with diminishing returns"
    )
    underexplored_domains: list[str] = Field(
        default_factory=list,
        description="Domains with potential"
    )

    # Cost tracking
    total_cost_usd: float = Field(0.0)
    cost_per_curated: float = Field(0.0)

    # Identified issues
    issues: list[str] = Field(
        default_factory=list,
        description="Key issues identified"
    )
    opportunities: list[str] = Field(
        default_factory=list,
        description="Improvement opportunities"
    )


class StrategyProposal(BaseModel):
    """Proposal from L1 Strategist with prioritized mutations."""

    generated_at: datetime = Field(default_factory=datetime.now)
    based_on_observation: str = Field(
        ...,
        description="Observation report timestamp"
    )

    mutations: list[Mutation] = Field(
        default_factory=list,
        description="Proposed mutations in priority order"
    )

    rationale: str = Field(
        ...,
        description="Overall strategy rationale"
    )

    expected_outcomes: list[str] = Field(
        default_factory=list,
        description="Expected improvements"
    )

    risks: list[str] = Field(
        default_factory=list,
        description="Potential risks"
    )
